#! /bin/bash
#
# /etc/init.d/doorpi
#
### BEGIN INIT INFO
# Provides: doorpi 
# Required-Start: $syslog $remote_fs 
# Required-Stop: $syslog $remote_fs
# Default-Start: 2 3 4 5 
# Default-Stop: 0 1 6 
# Short-Description: DoorPi 
# Description: VoIP Intercom Service DoorPi
### END INIT INFO

DOORPI_PATH=/home/pi/DoorPi/

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    python $DOORPI_PATH/doorpi/service.py start --configfile /home/pi/DoorPi/conf/doorpi.ini
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python $DOORPI_PATH/doorpi/service.py stop
    ;;
  restart)
    echo "Restarting server"
    $0 stop
    $0 start
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/doorpi.sh {start|stop|restart}"
    exit 1
    ;; esac
exit 0
