#! /bin/bash
#
# /etc/init.d/doorpi
#
### BEGIN INIT INFO
# Provides: doorpi 
# Required-Start: $syslog $remote_fs 
# Required-Stop: $syslog $remote_fs
# Default-Start: 2 3 4 5 
# Default-Stop: 0 1 6 
# Short-Description: DoorPi 
# Description: VoIP Intercom Service DoorPi
### END INIT INFO

DOORPI_PATH=/home/DoorPI

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    python $DOORPI_PATH/doorpi/main.py start --configfile $DOORPI_PATH/conf/doorpi.cfg
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python $DOORPI_PATH/doorpi/main.py stop
    ;;
  restart)
    echo "Restarting server"
    $0 stop
    $0 start
    ;;
  status)
    echo "Query Status:"
    # query status from doorpi
    python $DOORPI_PATH/doorpi/main.py status
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;; esac
exit 0
